### ISSUE TITLE
Eliminate flickering/flashing on refresh

### ISSUE THREAD

**Issue by frabjous** [ahrm/sioyek#165]
Thanks for making such a neat PDF viewer with such nice features. I am considering making it my main PDF viewer.

However, there is one feature preventing me from doing so, which is a flicker/flash-free reloading experience.

I like to have a PDF preview of my LaTeX and markdown documents which automatically refreshes it as I type. I've written [a neovim plugin](https://bitbucket.org/frabjous/knap/) that makes this possible, and you'll even see I recently added instructions for making it work with Sioyek to the README.

Sioyek has a nice feature of auto-reloading on changes, which works well for this. However, when it does so, the page flashes solid white (or solid black when colors inverted) and so creates a flickering as the document reloads.

You can see what I mean in the attached video. There I show the contrast with [llpp](https://wiki.archlinux.org/title/Llpp), which does not have this problem. Barebones MuPDF does not have this problem either, although Zathura does. (PDF viewers with non-MuPDF backends typically aren't fast enough to do this well.)

Anyway, this can be very distracting when you're trying to focus on writing.

Full disclosure, I was one of the people who convinced the dev of llpp to fix this issue in an earlier version; see the [now-closed issue](https://github.com/moosotc/llpp/issues/12) on their bug tracker. If he could make it work, maybe you can too!

https://user-images.githubusercontent.com/305948/158003852-01ac75e5-9108-4235-a539-eac0df434437.mp4

**Comment by ahrm** [comment]
Should be fixed in b461a6f7456a2992b2f78bce8b77cb20dc5e4190.

**Comment by frabjous** [comment]
Wow, thank you for working on this so far. I am really impressed.

This is a huge improvement.

At this point I feel as though I'm nitpicking, when you've worked so hard to create a really awesome thing, but it's still not as good as llpp.

You know how it works better than I, but it seems to flash back to an earlier, cached, version of the page as a background. However, it always seems to be a few reloads behind, so all the subsequent changes flicker/flash. This is especially noticeable if you delete a big piece of text and it flashes back into view as you type. See the attached video.

Eventually it updates what it uses as background, but it's still always behind a few. Compare with llpp once again.

This is really not so terrible; I can certainly live with it. But if you did think you could make it work as well as llpp, well, I'd be over the moon.


https://user-images.githubusercontent.com/305948/158023576-7f5811b9-6ea2-47ee-b940-c726381417f0.mp4

**Comment by ahrm** [comment]
Does 208f579ba240b67104c57dc7bae7b4fc01cd8e36 fix the issue?

**Comment by frabjous** [comment]
Oh, wow, yes. That seems to be perfect. This is amazing. I'm going to make Sioyek the default for my plugin. 

Do you take donations?

(Closing.)

**Comment by ahrm** [comment]
> Do you take donations?

Unfortunately for me, I live in Iran which is under heavy sanctions so I can't set up github sponsors or paypal or anything. So I don't think there is an easy way for you to donate to me. Thanks for the offer though :) .
