### ISSUE TITLE
Cannot permanently delete highlights

### ISSUE THREAD

**Issue by jmburgos** [ahrm/sioyek#583]
Hi Ali,

When I delete some highlights (either using dh, or by editing the list of highlights) and then close the pdf file, the highlights reappear when I open the pdf again.  I am using version 2.0.0-1, under Linux Fedora, installed as an appimage.  I had the same issue with the previous version.  

This is my prefs_user.config:

```
dark_mode_contrast 0.5
startup_commands             fit_to_page_width_smart
font_size 20
use_legacy_keybinds 0
show_document_name_in_statusbar 1

```
Do you know what could be the issue?

Many thanks!

**Comment by jmburgos** [comment]
Strangely, I noticed that under `~/.local/share I have these two folders:

```
~/.local/share/sioyek
~/.local/share/Sioyek
```
The floder with the lower caps "sioyek" contains older version of the databases than those on the "Sioyek" folder.  I wonder if the issue may be due to a typo in the name of the default path to the databases?

**Comment by ahrm** [comment]
When you open sioyek from command line it should print the path of its database files. I think appimage builds do use the `Sioyek` folder. When you delete a highlight is there any error message in the command line?
Also is it just highlights? Can you delete bookmarks? Can you add highlights?

**Comment by jmburgos** [comment]
Yes, it is using `Sioyek`.  And yes, I can add highlights, but I cannot delete them permanently.  I can delete them with no error message, but when I reopen the pdf file the highlights are back.  Bookmarks I can add and delete with no problem.

**Comment by ahrm** [comment]
That's … weird. Does it happen in all files or is it specific to a single file?

**Comment by jmburgos** [comment]
It is happening on all files I am testing.

I added this to my configuration file, to test if there was some issue with path names:

`shared_database_path /home/julian/.local/share/sioyek/shared.db`

But the problem is still ongoing.

**Comment by ahrm** [comment]
I added a new configuration option named `debug` you can enable it in `prefs_user.config` by adding
```
debug 1
```
When it is enabled, we print the SQL query used to delete the highlights. There are experimental builds with this feature here: https://github.com/hexomancer/sioyek/releases/tag/v0.31.420.

Can you:
1. Use a new shared database path (because you are going to share it with me, so it is better to be brand new so none of your information is in it)
2. Add highlights to the tutorial document
3. Make sure you can not delete the highlights
4. Share the new database file and the query printed in the console (when `debug` is on) here

**Comment by jmburgos** [comment]
With version 0.31.420 I still cannot remove highlights.  

I opened the tutorial and put a couple of highlights.  Then I tried to delete them.  This is what I got on the console:

```
julian@hafhrygla ~/D/org_files> sioyek /home/julian/sioyek/Sioyek_tutorial.pdf
default_config_path: /tmp/.mount_sioyekK7CutM/usr/bin/prefs.config
default_keys_path: /tmp/.mount_sioyekK7CutM/usr/bin/keys.config
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /home/julian/.config/sioyek/prefs_user.config
user_config_path: [ 2 ] /home/julian/.local/share/Sioyek/prefs_user.config
user_config_path: [ 3 ] /home/julian/.config/sioyek/prefs_user.config
user_keys_path: [ 0 ] /etc/xdg/sioyek/keys_user.config
user_keys_path: [ 1 ] /home/julian/.config/sioyek/keys_user.config
user_keys_path: [ 2 ] /home/julian/.local/share/Sioyek/keys_user.config
user_keys_path: [ 3 ] /home/julian/.config/sioyek/keys_user.config
database_file_path: /home/julian/.local/share/Sioyek/test.db
local_database_file_path: /home/julian/.local/share/Sioyek/local.db
global_database_file_path: /home/julian/test/shared.db
tutorial_path: /home/julian/.local/share/Sioyek/tutorial.pdf
last_opened_file_address_path: /home/julian/.local/share/Sioyek/last_document_path.txt
shader_path: /tmp/.mount_sioyekK7CutM/usr/bin/shaders
Creating shared memory block...
Shared memory created: this is the primary application.
Starting IPC server...
IPC server started.
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: found duplicate fz_icc_link in the store
warning: found duplicate fz_icc_link in the store
DELETE FROM highlights where document_path='1717ab11ed0a7a1ec76d9403108c098f'AND abs(begin_x-(-146)) < 0.01 AND abs(begin_y-(250)) < 0.01 AND abs(end_x-(-53)) < 0.01 AND abs(end_y-(265)) < 0.01;
DELETE FROM highlights where document_path='1717ab11ed0a7a1ec76d9403108c098f'AND abs(begin_x-(-23)) < 0.01 AND abs(begin_y-(290)) < 0.01 AND abs(end_x-(22)) < 0.01 AND abs(end_y-(291)) < 0.01;
```

When I open the pdf the highlihts are still there.

I could not upload the database, but you can find it in this link:

https://www.dropbox.com/s/7za3zgefzycatt8/shared.db?dl=0

**Comment by ahrm** [comment]
The issue seems to be c++ rounding floating point values to integers, which is weird because by default they are supposed to have 6 significant digits. I made a build where we manually specify the significant digits here: https://github.com/hexomancer/sioyek/releases/tag/v0.31.422.

Is the issue fixed in this build?

**Comment by jmburgos** [comment]
No, I am still having the issue.

Would it be useful if I try with older builds to see at which point this issue started to happen?  When I started to use sioyek I could delete highlights with no problem.

**Comment by ahrm** [comment]
> Would it be useful if I try with older builds to see at which point this issue started to happen?

No I am pretty sure this is the commit that introduces the issue: https://github.com/ahrm/sioyek/commit/92ddb111772c3a23723a0ac8cfdcf6d54d7cf1e0

I don't know why floating point values are rounded in your OS though, it should not be an OS-dependent thing.

**Comment by ahrm** [comment]
Can you enable the debug mode in the new build and paste the console output when trying to delete the highlights?

**Comment by jmburgos** [comment]
The issue is still a problem with the latest build (0.31.422).  This is what I get when I try to delete a highligt:

```
~/sioyek $ sioyek Sioyek_tutorial.pdf 
default_config_path: /tmp/.mount_sioyekSRb2BQ/usr/bin/prefs.config
default_keys_path: /tmp/.mount_sioyekSRb2BQ/usr/bin/keys.config
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /home/julian/.config/sioyek/prefs_user.config
user_config_path: [ 2 ] /home/julian/.local/share/Sioyek/prefs_user.config
user_config_path: [ 3 ] /home/julian/.config/sioyek/prefs_user.config
user_keys_path: [ 0 ] /etc/xdg/sioyek/keys_user.config
user_keys_path: [ 1 ] /home/julian/.config/sioyek/keys_user.config
user_keys_path: [ 2 ] /home/julian/.local/share/Sioyek/keys_user.config
user_keys_path: [ 3 ] /home/julian/.config/sioyek/keys_user.config
database_file_path: /home/julian/.local/share/Sioyek/test.db
local_database_file_path: /home/julian/.local/share/Sioyek/local.db
global_database_file_path: /home/julian/test/shared.db
tutorial_path: /home/julian/.local/share/Sioyek/tutorial.pdf
last_opened_file_address_path: /home/julian/.local/share/Sioyek/last_document_path.txt
shader_path: /tmp/.mount_sioyekSRb2BQ/usr/bin/shaders
Creating shared memory block...
Shared memory created: this is the primary application.
Starting IPC server...
IPC server started.
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: undefined link destination
warning: unknown link uri '(null)'
warning: found duplicate fz_icc_link in the store
warning: found duplicate fz_icc_link in the store
DELETE FROM highlights where document_path='1717ab11ed0a7a1ec76d9403108c098f'AND abs(begin_x-(-134)) < 0.01 AND abs(begin_y-(252)) < 0.01 AND abs(end_x-(-85)) < 0.01 AND abs(end_y-(257)) < 0.01;

```

**Comment by ahrm** [comment]
I couldn't reproduce the issue on a VM install of fedora 37. Is there any weird specific thing about your system which could be relevant? eg:

* Which version of fedora are you using?
* Which architecture?
* What is your hardware?

**Comment by jmburgos** [comment]
Operating System: Fedora Linux 37 (Workstation Edition)
     CPE OS Name: cpe:/o:fedoraproject:fedora:37
          Kernel: Linux 6.0.18-300.fc37.x86_64
    Architecture: x86-64
 Hardware Vendor: Dell Inc.
  Hardware Model: Precision 5550
Firmware Version: 1.19.0

**Comment by ahrm** [comment]
Okay I added a `highlight_delete_threshold` option in https://github.com/hexomancer/sioyek/releases/tag/v0.31.424. You can probably fix the problem by setting it to a higher value, for example:
```
highlight_delete_threshold 1
```

**Comment by jmburgos** [comment]
Yes!! This solved the issue.  Thank you so much for looking into this.  
And thank you for a very good software.  I have recommended it to my colleagues at work as a better alternative to Acrobat for reading academic documents.

**Comment by ahrm** [comment]
Thanks. I must add that this is a dirty fix to this problem. The original issue (where floating point values were rounded on your system, while they shouldn't be) is still present. I genuinely have no idea why this is the case and I am very curious to find out.

**Comment by naquad** [comment]
The issue reproduces in the 2.0.0: after deleting highlights and restarting Sioyek the deleted highlights are restored.
The referenced command `highlight_delete_threshold` is not recognized.

Demo

![sioyek_record](https://github.com/user-attachments/assets/09c34bfd-12e3-4ac6-a4be-6a1ff95c64a6)

**Comment by ahrm** [comment]
Does the issue happen in the preview release here: https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0 ?

**Comment by naquad** [comment]
Great success! The referenced release is handling the deletion of the highlight as expected.

While you are here, can I ask if there's a plan to improve the annotation sync between the document and the Sioyek viewer? Currently, I'm messing with this: https://gist.github.com/naquad/b1d04b74ba890fdc7a79a5a568729085 - but it is a very coarse solution. Thank you.
